name: Deletar Branch Após Merge ou Fechamento de PR

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Deletar o branch no fork
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')
          if [[ "$BRANCH_NAME" != "main" && "$BRANCH_NAME" != "master" ]]; then
            echo "Deletando o branch $BRANCH_NAME..."
            git push origin --delete $BRANCH_NAME
          else
            echo "Não é possível deletar o branch main ou master"
          fi
