name: Delete branch on fork

on:
  pull_request:
    types:
      - closed
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch on fork
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          OWNER=${{ github.event.pull_request.head.repo.owner.login }}
          REPO=${{ github.event.pull_request.head.repo.name }}
          echo "Deleting branch $BRANCH_NAME in fork $OWNER/$REPO"
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO/git/refs/heads/$BRANCH_NAME
